const express = require("express")
const hbs = require("hbs")
const bodyParser = require("body-parser")
const methodOverride = require("method-override")
const flash = require("connect-flash")
const cookieParser = require("cookie-parser")
const session = require("express-session")
const passport = require("passport")

const app = express()
